CREATE TABLE IF NOT EXISTS Employee (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  email VARCHAR(250) NOT NULL UNIQUE,
  firstname VARCHAR(500),
  lastname VARCHAR(250),
  password VARCHAR(250) NOT NULL
);


CREATE TABLE IF NOT EXISTS Ticket (
  id INT AUTO_INCREMENT PRIMARY KEY,
  employeeid INT NOT NULL,
  department VARCHAR(250) NOT NULL,
  details VARCHAR(250) NOT NULL,
  createDate DATE DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (employeeid) REFERENCES Employee(id)
);
